#ifndef McxAPIReturnCodes_INCLUDED
#define McxAPIReturnCodes_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

#define STL_ERR_SUCCESS												( 0)
#define STL_ERR_INVALID_DEVICE_NUMBER								(-1)		
#define STL_ERR_VERSION_ERROR										(-2)		
#define STL_ERR_DEVICE_NOT_FOUND									(-3)		
#define STL_ERR_FAILED_TO_OPEN_DEVICE								(-4)		
#define STL_ERR_FAILED_TO_GET_DESCRIPTORS							(-5)		
#define STL_ERR_FAILED_TO_CONFIGURE_FPGA							(-6)		
#define STL_ERR_FAILED_TO_READ_DEVICE_PORT							(-7)		
#define STL_ERR_FAILED_TO_SET_DEVICE_PORT							(-8)		
#define STL_ERR_DEVICE_POWER_SUPPLY_ERRPR							(-9)		
#define STL_ERR_FAILED_TO_START_FPGA_CONFIG							(-10)		
#define STL_ERR_FAILED_TO_OPEN_FPGA_FILE							(-11)		
#define STL_ERR_FAILED_TO_WRITE_FPGA_CHUNK							(-12)		
#define STL_ERR_FAILED_TO_LOAD_FPGA									(-13)	
#define STL_ERR_NOT_IMPLEMENTED										(-14)	
#define STL_ERR_DATABLOCK_SIZE_EXCEEDS_LIMIT						(-15)	
#define STL_ERR_QUSB_WRITE_COMMAND_FAILED							(-16)	
#define STL_ERR_QUSB_READ_FAILED									(-17)	
#define STL_ERR_QUSB_WRITE_FAILED									(-18)	
#define STL_ERR_TOO_MANY_ELEMENTS_FOR_MEM_SPCAE						(-19)	
#define STL_ERR_NULL_POINTER_PARAMETER								(-20)	
#define STL_ERR_STRING_TOO_LONG										(-21)	
#define STL_ERR_INVALID_DIRECTORY_NAME								(-22)	
#define STL_ERR_FAILED_TO_ALLOCATE_MEMORY							(-23)	
#define STL_ERR_H009_DEVICE_ID_MUST_BE_EVEN							(-24)
#define STL_ERR_PP194_ELEMENT_ON_ODD_DEVICE_ID						(-25)
#define STL_ERR_DEVICE_NOT_MAPPED									(-26)
#define STL_ERR_LONG_READ_5_LSB_NOT_0								(-27)
#define STL_ERR_TOO_MANY_WRONG_SYMBOLS_IN_WM						(-28)
#define STL_ERR_DEVICE_NOT_INITIALIZED								(-29)
#define STL_ERR_PP194_DEVICE_ID_MUST_BE_EVEN						(-30)

#define STL_ERR_DEVICE_BUSY											(-51)
#define STL_ERR_DEVICE_WAS_FORCED_HW_RESET_DURING_STOP				(-52)

#define STL_ERR_PCI_READ_WIDTH_NOT_MODULU_4							(-100)	

#define STL_ERR_FAILED_TO_CREATE_THREAD								(-1000)	

#define STL_ERR_BUSLIST_ALREADY_EXISTS								(-2000)		///User tried to create a buslist that was previously created.
#define STL_ERR_ELEMENT_ALREADY_EXISTS								(-2001)		///
#define STL_ERR_DATABLOCK_ALREADY_EXISTS							(-2002)		///
#define STL_ERR_DATABLOCK_SIZE_ASSINGMENT_ERROR						(-2003)		
#define STL_ERR_DATABLOCK_SIZE_TOO_SMALL							(-2004)		
#define STL_ERR_MAPPING_UNREADY_CONSTRUCTS							(-2005)		
#define STL_ERR_BUSLIST_CONTAINS_TOO_MANY_ELEMENTS					(-2006)		
#define STL_ERR_BUSLIST_IS_RUNNING									(-2007)		
#define STL_ERR_CODE_IN_REG_1A_INCORRECT							(-2008)		
#define STL_ERR_WRITING_TO_UNINITIALIZED_DATABLOCK					(-2009)		
#define STL_ERR_WRITING_TO_UNINITIALIZED_ELEMENT					(-2010)		
#define STL_ERR_WRITING_TO_UNMAPPED_DATABLOCK						(-2011)		
#define STL_ERR_ACCESSING_INVALID_DEVICE_ID							(-2012)		
#define STL_ERR_REQUESTED_ID_EXCEEDED_MAX_ALLOWED					(-2013)
#define STL_ERR_ELEMENT_IS_RUNNING									(-2014)
#define STL_ERR_DATABLOCK_IS_RUNNING								(-2015)
#define STL_ERR_REQUESTED_ID_UNINITIALIZED							(-2016)
#define STL_ERR_DATABLOCK_NOT_MAPPED_TO_ELEMENT						(-2017)
#define STL_ERR_ELEMENT_NOT_MAPPED_TO_BUSLIST						(-2018)
#define STL_ERR_READ_DATA_WHILE_TX_NOT_ALLOWED						(-2019)
#define STL_ERR_COMMAND_MODE_CODE_NOT_SUPPORTED						(-2020)
#define STL_ERR_READING_EMPTY_BUFFER								(-2021)
#define STL_ERR_NOT_IN_RUNNING_MODE									(-2022)
#define STL_ERR_STOP_RUN_FAILED										(-2023)
#define STL_ERR_START_RUN_FAILED									(-2024)
#define STL_ERR_GET_TIMETAG_FAILED_DATA_INCONSISTENT				(-2025)
#define STL_ERR_TIME_REQUESTED_NOT_IN_VALID_RANGE					(-2026)
#define STL_ERR_TIME_VALUE_REQUESTED_IS_INVALID						(-2027)
#define STL_ERR_MESSGE_NUMBER_TO_INSERT_ERROR_IS_INVALID			(-2028)
#define STL_ERR_WORD_NUMBER_TO_INSERT_ERROR_IS_INVALID				(-2029)
#define STL_ERR_NO_ERROR_SPECIFIED									(-2030)
#define STL_ERR_SYNC_INJECTION_PARAM_INVALID						(-2031)
#define STL_ERR_SPECIFIED_ERROR_INJECTION_NOT_SUPPORTED				(-2032)
#define STL_ERR_ZERO_CROSSING_INJECTION_PARAM_INVALID				(-2033)
#define STL_ERR_DEVICE_MEMORY_FULL									(-2034) /// During mRt start the datablock's allocation spiled over the memory limit of the device
#define STL_ERR_RUI_0_ENABLE_IS_REDUNDANT_IN_PP194					(-2035) 
#define STL_ERR_ELEMENT_NOT_INITIALIZED								(-2036) 
#define STL_ERR_DATABLOCK_SIZE_TOO_BIG								(-2037) 
#define STL_ERR_BUSLIST_IS_NOT_IN_RUNNING_MODE						(-2038) 
#define STL_ERR_SPECIFIED_PROTOCOL_NOT_SUPPORTED					(-2039) 
#define STL_ERR_INVALID_PROTOCOL_TYPE								(-2040) 
#define STL_ERR_MULTI_SHOTS_NOT_SUPPORTED							(-2041) 
#define STL_ERR_BUSLIST_PASSIVE_PHASE_NOT_FOUND						(-2042) 
#define STL_ERR_DATA_VECTOR_OVERFLOW								(-2043) 
#define STL_ERR_DEPRECATED_FUNCTION									(-2044) 

#define STL_ERR_INVALID_ARGUMENTS									(-2200) 
#define STL_ERR_NULL_POINTER										(-2201) 
#define STL_ERR_READ_FAILED											(-2202) 
#define STL_ERR_WRITE_FAILED										(-2203) 
//#define STL_ERR_DEVICE_BUSY										(-2204) 
#define STL_ERR_TIMETAG_ZERO_READ_AGAIN								(-2205) 
#define STL_ERR_RT_DELAY_RESPONSE_FAILED							(-2206) 
#define STL_ERR_RT_ILLIGAL											(-2207) 

#define STL_ERR_CANNOT_SEND_ON_RX_CHANNEL							(-2300)// Arinc 429
#define STL_ERR_CANNOT_GET_ON_TX_CHANNEL							(-2301)// Arinc 429
#define STL_ERR_TIMEOUT												(-2302)// Arinc 429
#define STL_ERR_IO_OVERFLOW											(-2303)// Arinc 429
#define STL_ERR_A429_SIGNATURE_MISSING								(-2304)// Arinc 429
#define STL_ERR_A429_DEVICE_ALREADY_OPENED							(-2305)// Arinc 429
#define STL_ERR_A429_BUFFER_SIZE									(-2306)
// licensing
#define STL_ERR_LICENSE_PARAM_NOT_FOUND								(-2350) 
#define STL_ERR_LICENSE_STRING_NOT_FOUND							(-2351) 
#define STL_ERR_LICENSE_STRING_TOO_SHORT							(-2352) 
#define STL_ERR_LICENSE_INVALID_FEATURE								(-2353) 
#define STL_ERR_LICENSE_INVALID_CHECKSUM							(-2354) 
#define STL_ERR_LICENSE_INVALID_KEY									(-2355)
#define STL_ERR_LICENSE_PROTOCOL_DISABLED							(-2356)
#define STL_ERR_LICENSE_SINGLE_DEVICE_PERMISSION					(-2357)
#define STL_ERR_LICENSE_DIGIBUS_REQUIRE_1553						(-2358)
#define STL_ERR_LICENSE_BUSLIST_CONTAINS_UNLICENSED_PP194_MESSAGE	(-2359)
#define STL_ERR_LICENSE_BUSLIST_CONTAINS_UNLICENSED_1553_MESSAGE	(-2360)
#define STL_ERR_LICENSE_H009_UNLICENSED								(-2361)
#define STL_ERR_LICENSE_1553_UNLICENSED								(-2362)
#define STL_ERR_LICENSE_PP194_UNLICENSED							(-2363)
#define STL_ERR_LICENSE_EBR_UNLICENSED								(-2364)
#define STL_ERR_LICENSE_DIGIBUS_F16_UNLICENSED						(-2365)
#define STL_ERR_LICENSE_ENGINEERING_UNITS_UNLICENSED				(-2366)
#define STL_ERR_LICENSE_WIRING_FAULT_LOCATION_UNLICENSED			(-2367)
#define STL_ERR_LICENSE_SMART_CYBER_EMULATION_UNLICENSED			(-2368)
#define STL_ERR_LICENSE_NO_LICENSED_FEATURES_FOUND					(-2369)
#define STL_ERR_LICENSE_REQUIRED_AND_NOT_FOUND_1553_ONLY_ENABLED	(-2370) 
#define STL_ERR_LICENSE_EXPIRED										(-2371) 
#define STL_ERR_LICENSE_RS485_422_UNLICENSED						(-2372)
#define STL_ERR_LICENSE_ARINC429_UNLICENSED							(-2373)
#define STL_ERR_LICENSE_SCOPE_UNLICENSED							(-2374)

#define STL_ERR_FUNCTION_NOT_IMPLEMENTED							(-3000)		
#define STL_ERR_SW_POINTER_INPUT_IS_ODD								(-3001)
#define STL_ERR_ODD_NUMBER_OFF_ELEMENTS_IN_HOST_BUFFER				(-3002)
#define STL_ERR_LICENSE_FILE_MISSING_OR_DAMAGED						(-3003)
#define STL_ERR_LICENSE_FILE_EMPTY									(-3004)
#define STL_ERR_FILE_OPEN_FAILED									(-3050)

#define STL_ERR_ETH_W_SOCKET_FAIL									(-7000)
#define STL_ERR_ETH_R_SOCKET_FAIL									(-7001)
#define STL_ERR_ETH_W_SOCKET_ADDRESS_ERROR							(-7002)
#define STL_ERR_ETH_R_SOCKET_ADDRESS_ERROR							(-7003)
#define STL_ERR_ETH_W_DATA_BUFF_SIZE								(-7004)
#define STL_ERR_ETH_W_REQUEST_TIMEOUT								(-7005)
#define STL_ERR_ETH_R_SENDTO_REQUEST_TIMEOUT						(-7006)
#define STL_ERR_ETH_R_RECVFROM_REQUEST_TIMEOUT						(-7007)
#define STL_ERR_ETH_SERVER_LIST_ITEMS								(-7008)

#define STL_ERR_NOT_SUPPORTED_FOR_LINUX								(-9000)
#define STL_ERR_NOT_SUPPORTED_FOR_VXWORKS							(-9001)

#ifdef __cplusplus
}
#endif



#endif // McxAPIReturnCodes_INCLUDED
